### ISSUE TITLE
Upgrade to 0.7.0 breaking

### ISSUE THREAD

**Issue by bogdancss** [jonkwheeler/styled-components-snippets#5]
Hey there,

I just upgraded the plugin to 0.7.0 and am getting these errors when launching Atom:

```Failed to load snippets from '/Users/.../.atom/packages/styled-components-snippets/snippets/styled-components-snippets.cson'```

```/Users/.../.atom/packages/styled-components-snippets/snippets/styled-components-snippets.cson: Duplicate key 'createGlobalStyle'```

The snippets don't work either (`sc` + `Tab`)

**Comment by jonkwheeler** [comment]
@b0gd4n can you upgrade again? This PR should have fixed it https://github.com/jonkwheeler/styled-components-snippets/pull/6

I just published 0.8.0.

**Comment by bogdancss** [comment]
@jonkwheeler all good now - thank you!

On a separate note, is there a way to edit the snippet to not add `;` at the end?

**Comment by jonkwheeler** [comment]
> On a separate note, is there a way to edit the snippet to not add ; at the end?

Hmm, I could, but that's not proper JS syntax. If you're using prettier, it'll automatically remove those on save. What is your setup?
